export const TOKEN_TYPE = 'erc20'
export const TOKEN_CONTRACT = '0x6B175474E89094C44Da98b954EedeAC495271d0F'
export const PAYMENTS_CSV_HEADING = 'token_type,token_address,receiver,value,id'
export const DAI_REDEMPTIONS_ACCOUNT_ID = 'zJ1wFJh6cgT8QOl8VFL8lw'
export const NEEDS_LIKES_STATUS = 'Needs likes'
export const CONFIRMED_STATUS = 'Confirmed'
export const OPTED_OUT_STATUS = 'Opted out'
export const NEEDS_OPT_OUT_STATUS = 'Needs opt out'
